# Generated by Django 5.1.3 on 2024-12-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_tradingalert_alter_tradingviewalert_options_and_more'),
    ]

    operations = [
    ]
