# Generated by Django 5.1.3 on 2024-12-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_create_default_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingviewalert',
            name='action',
        ),
        migrations.RemoveField(
            model_name='tradingviewalert',
            name='message',
        ),
        migrations.RemoveField(
            model_name='tradingviewalert',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='tradingviewalert',
            name='symbol',
        ),
        migrations.AlterField(
            model_name='tradingviewalert',
            name='text_data',
            field=models.TextField(),
        ),
    ]
